# Generated by Django 4.1 on 2023-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todaapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=250, verbose_name="Task Name"),
        ),
    ]
