# Generated by Django 4.1 on 2023-07-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todaapp", "0002_alter_task_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1997-05-20"),
            preserve_default=False,
        ),
    ]
